//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playlister.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bridge_Combo_ID
    {
        public long Bridge_Combo_ID1 { get; set; }
        public long Song_ID { get; set; }
        public int Playlist_ID { get; set; }
    
        public virtual Playlist Playlist { get; set; }
        public virtual Song Song { get; set; }
    }
}
