//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playlister.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Combo_Bridge_ID
    {
        public int Playlist_ID { get; set; }
        public System.Guid HREF { get; set; }
        public long Combo_Bridge_ID1 { get; set; }
    
        public virtual Playlist Playlist { get; set; }
        public virtual Song_Store Song_Store { get; set; }
    }
}
