//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playlister.dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlaylisterDEV : DbContext
    {
        public PlaylisterDEV()
            : base("name=PLaylisterDEV")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bridge_Combo_ID> Bridge_Combo_ID { get; set; }
        public DbSet<Party> Parties { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<Person_Role> Person_Roles { get; set; }
        public DbSet<Playlist> Playlists { get; set; }
        public DbSet<Profile> Profiles { get; set; }
        public DbSet<Role_Permission> Role_Permissions { get; set; }
        public DbSet<Song> Songs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
