//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playlister.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public Song()
        {
            this.Bridge_Combo_ID = new HashSet<Bridge_Combo_ID>();
        }
    
        public long Song_ID { get; set; }
        public string HREF { get; set; }
        public string Song_Name { get; set; }
        public string Artist { get; set; }
        public string Popularity { get; set; }
    
        public virtual ICollection<Bridge_Combo_ID> Bridge_Combo_ID { get; set; }
    }
}
